{
 "title": "Backup Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Backup Monitoring",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=\"backup-manager\"} |= ``"
    },
    {
     "direction": "backward",
     "expr": "{container_name=\"postgres-db\"} |= ``"
    },
    {
     "direction": "backward",
     "expr": "{container_name=\"pentaho-carte\"} |= ``"
    }
   ]
  },
  {
   "title": "Base Directory Metrics",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time(base_directory_file_count[1d])",
     "legendFormat": "Base file count"
    },
    {
     "expr": "avg_over_time(base_directory_size_bytes[1d])",
     "legendFormat": "Raw size"
    }
   ]
  },
  {
   "title": "Wal Directory Metrics",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time(wal_directory_file_count[1d])",
     "legendFormat": "Wal file count"
    },
    {
     "expr": "avg_over_time(wal_directory_size_bytes[1d])",
     "legendFormat": "Wal size"
    }
   ]
  },
  {
   "title": "Job Metrics",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=\"postgres-db\"} |~ \"Persisted encrypted WAL file\"",
     "maxLines": 1
    },
    {
     "direction": "backward",
     "expr": "{container_name=\"pentaho-carte\"} |= `jb_base_backup - Job execution finished`",
     "maxLines": 1
    },
    {
     "direction": "backward",
     "expr": "{container_name=\"pentaho-carte\"} |= `jb_wal_backup - Job execution finished`",
     "maxLines": 1
    },
    {
     "direction": "backward",
     "expr": "{container_name=\"backup-manager\"} |= `Base Backup and cleanup completed`",
     "maxLines": 1
    },
    {
     "direction": "backward",
     "expr": "{container_name=\"pentaho-carte\"} |= `jb_file_metrics - Job execution finished`",
     "maxLines": 1
    }
   ]
  }
 ]
}